# Generated by Django 3.2 on 2021-12-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MMSMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=30)),
                ('mime_type', models.CharField(max_length=30)),
                ('media_sid', models.CharField(max_length=35)),
                ('message_sid', models.CharField(max_length=35)),
                ('media_url', models.CharField(max_length=150)),
                ('content', models.TextField()),
            ],
        ),
    ]
